### PR TITLE
Set mutex flag to avoid getting MCT1 twice

### PR DESCRIPTION
**Pull request by jwulf**
This is a simple check to see if a player already has MCT1 and an early exit to avoid getting twice.

### CODE REVIEW

**Comment by jwulf** [comment]
This will stop the player getting it more than once. 

It also takes off the countdown, and replaces it with an effect where the player progressively slows down until they are struck by lightning.

**Comment by jwulf** [comment]
I took a look at `State.ts`- at the moment you create the state if it doesn't exist, so there is no method atm to check if a state exists. `getState()` would be more accurately titled `getOrCreateState()`.

**Comment by tim-marwick** [comment]
@jwulf Re State, see `_ensureCompleteState()`, that creates it if it doesn't exist.

**Comment by tim-marwick** [comment]
Merging, but still need to update the added code to use the State utility functions.

**Pull request merged**
